schemas:
  bootstrap: 8000
  cakeheads: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://build-cakeheads.pantheonsite.io/themes/custom/cakeheads/favicon.ico'
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
table_responsive: '-1'
navbar_position: fixed-top
cdn_theme: bootstrap
cdn_cache_ttl_versions: '604800'
cdn_cache_ttl_themes: '604800'
cdn_cache_ttl_assets: '0'
cdn_cache_ttl_library: '0'
reset_http_request_cache: ''
table: ''
